name: Setup WordPress

description: Install PHP, Configure Apache and MySQL, Install WordPress...

inputs:
  php-version:
    required: false
    type: string
    default: ""
  php-ini-values:
    required: false
    type: string
    default: ""
  wp-version:
    required: false
    type: string
    default: "latest"
  wp-abspath:
    required: false
    type: string
    default: "/var/www/html"
  wp-url:
    required: false
    type: string
    default: "http://localhost/"  # Must be ends with "/".
  wp-username:
    required: false
    type: string
    default: "admin"
  wp-password:
    required: false
    type: string
    default: "password"
  wp-language:
    required: false
    type: string
    default: "en_US"

runs:
  using: "composite"
  steps:
    # todo: Problem with `ubuntu-24.04`'s default PHP (8.3) 
    - id: setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        ini-values: ${{ inputs.php-ini-values }}
        # todo `tools: wp-cli`, that place `wp` executable at "/usr/local/bin/wp".
      env:
        update: "true"

    - name: Configure Apache
      run: |
        sudo a2enmod proxy_fcgi setenvif rewrite ssl
        sudo a2enconf php${{ steps.setup-php.outputs.php-version }}-fpm
        sudo a2ensite default-ssl
        cat <<EOF | sudo tee /etc/apache2/conf-available/wordpress.conf
        <Directory ${{ inputs.wp-abspath }}>
            AllowOverride All
        </Directory>
        EOF
        sudo a2enconf wordpress
        sudo systemctl start apache2
        sudo chown -R www-data:www-data /var/www
        sudo chmod -R 755 /var/www
        sudo chown -R www-data:www-data ${{ inputs.wp-abspath }}
        sudo chmod -R 755 ${{ inputs.wp-abspath }}
        sudo rm -rf ${{ inputs.wp-abspath }}/*
      shell: bash -v {0}
      continue-on-error: true
    - name: Apache bootlogs
      run: |
        sudo systemctl status apache2
        sudo journalctl -xeu apache2
        cat /etc/apache2/sites-available/000-default.conf
        cat /etc/apache2/sites-available/default-ssl.conf
        sudo ls -laR /etc/ssl/certs
        cat stat /etc/ssl/certs/ssl-cert-snakeoil.pem
        sudo stat /etc/ssl/private/ssl-cert-snakeoil.key
      shell: bash -v {0}
      if: failure()
    - name: Check Apache is running
      run: sudo systemctl is-active --quiet apache2
      shell: bash
    - name: Check PHP-FPM is working
      run: |+
        echo "<?php echo chr(72).chr(101).chr(108).chr(108).chr(111).chr(32).chr(119).chr(111).chr(114).chr(108).chr(100).chr(33); ?>" | sudo tee test.php
        curl -s ${{ inputs.wp-url }}/test.php | grep "Hello world!" > /dev/null
        sudo rm test.php
      shell: bash
      working-directory: ${{ inputs.wp-abspath }}

    - name: Enable MySQL
      run: sudo systemctl start mysql.service
      shell: bash

    # https://make.wordpress.org/cli/handbook/guides/installing/
    - name: Install WP-CLI
      run: |+
        curl -s -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp
        wp --info
      shell: bash -v {0}

    - name: Setup WordPress
      run: |+
        sudo -u www-data wp core download --version=${{ inputs.wp-version }}
        sudo -u www-data wp config create --dbname=wordpress --dbuser=root --dbpass=root
        sudo -u www-data wp config set AUTOMATIC_UPDATER_DISABLED true --raw
        sudo -u www-data wp db create
        sudo -u www-data wp core install --url=${{ inputs.wp-url }} --title=Test --admin_user=${{ inputs.wp-username }} --admin_password=${{ inputs.wp-password }} --admin_email=admin@wordpress.local --skip-email
        sudo -u www-data wp language core install ${{ inputs.wp-language }} --activate
        sudo -u www-data wp theme install classic --activate
      shell: bash -v {0}
      working-directory: ${{ inputs.wp-abspath }}

    # Check by WP-CLI.
    - name: Check WP-CLI can access WordPress
      run: |
        sudo -u www-data wp db check
        sudo -u www-data wp core is-installed
        sudo -u www-data wp core version
      shell: bash -v {0}
      working-directory: ${{ inputs.wp-abspath }}

    # Dump.
    - run: curl -sL ${{ inputs.wp-url }}
      shell: bash -v {0}
      continue-on-error: true
    - run: curl -sL ${{ inputs.wp-url }}wp-admin/
      shell: bash -v {0}
      continue-on-error: true

    # Check.
    - id: is-wordpress-working
      name: Check WordPress is working
      run: |+
        curl -sL ${{ inputs.wp-url }} | grep "Hello world!" > /dev/null
        curl -sL ${{ inputs.wp-url }}wp-admin/ | grep "loginform" > /dev/null
      shell: bash
      continue-on-error: true
    - run: |+
        # Enable debug mode to get more error details.
        sudo -u www-data wp config set WP_DEBUG true --raw
        sudo -u www-data wp config set WP_DEBUG_LOG true --raw
        sudo -u www-data wp config set WP_DEBUG_DISPLAY true --raw

        # Refetch to trigger debug log.
        curl -sL ${{ inputs.wp-url }}
        curl -sL ${{ inputs.wp-url }}/wp-admin/

        # Dump log
        cat ./wp-content/debug.log

        # Stop job with error.
        false
      if: ${{ steps.is-wordpress-working.outcome == 'failure' }}
      shell: bash -v {0}
      working-directory: ${{ inputs.wp-abspath }}
